name: Atualizar Dados Contratações PNCP

on:
  schedule:
    - cron: '0 0 * * *'  # Vai rodar todo dia à meia-noite (você pode alterar o cronograma)
  workflow_dispatch:  # Permite rodar manualmente se necessário

jobs:
  update_data:
    runs-on: ubuntu-latest  # Ambiente que será usado para rodar o script

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v2  # Verifica o código no repositório

      - name: Configurar Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Versão do Python que será usada

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Executar script Python
        run: |
          python scripts/atualizar_dados.py  # Caminho para o seu script Python

      - name: Commit e Push dos arquivos gerados
        run: |
          git config --global user.name "Seu Nome"
          git config --global user.email "seuemail@dominio.com"
          git add .
          git commit -m "Atualizando os arquivos de dados PNCP"
          git push
