name: Atualizar Dados Contratações PNCP

on:
  schedule:
    - cron: "0 0 * * *"  # Isso fará o workflow rodar todos os dias à meia-noite
  workflow_dispatch:  # Isso permite rodar manualmente pela interface do GitHub
  push:
    branches:
      - main  # Ou a branch que você está utilizando
permissions:
  contents: write  # Permite escrita no repositório
  
jobs:
  update_data:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do repositório
      uses: actions/checkout@v2

    - name: Configurar Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Defina a versão do Python que você usa

    - name: Instalar dependências
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Executar script Python
      run: |
        python scripts/atualizar_dados.py

    - name: Limpar pasta de dados antigos
      run: |
        rm -rf dados_pncp/*  # Remove todos os arquivos da pasta de dados

    - name: Commit e push dos dados gerados
      run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add dados_pncp/*  # Adiciona os arquivos gerados
          git commit -m "Atualização dos dados das contratações PNCP"
          git push https://github-actions:${{ secrets.GITHUB_TOKEN }}@github.com/eduardo130796/portal_licitacoes.git
