name: Atualizar Dados Contratações PNCP

on:
  schedule:
    - cron: "0 0 * * *"  # Isso fará o workflow rodar todos os dias à meia-noite
  workflow_dispatch:  # Isso permite rodar manualmente pela interface do GitHub
  push:
    branches:
      - main  # Ou a branch que você está utilizando
permissions:
  contents: write  # Permite escrita no repositório
  
jobs:
  update_data:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do repositório
      uses: actions/checkout@v2

    - name: Configurar Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Defina a versão do Python que você usa

    - name: Instalar dependências
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Listar arquivos antes da exclusão
      run: ls -al dados_pncp/

    - name: Executar excluir pasta e criar novamente
      run: |
        rm -rf dados_pncp
        mkdir -p dados_pncp

    - name: Listar arquivos após a exclusão
      run: ls -al dados_pncp/

    - name: Remover arquivos do Git e criar pasta novamente
      run: |
        git rm -rf dados_pncp || true
        rm -rf dados_pncp
        mkdir -p dados_pncp
        
    - name: Limpar arquivos não rastreados
      run: git clean -fd

          
    - name: Executar script Python
      run: |
        python scripts/atualizar_dados.py

    

    # Step 3: Verificar que os arquivos foram gerados
    - name: Listar arquivos no diretório dados_pncp
      run: ls -al dados_pncp/
    
    # Step 4: Adicionar os arquivos gerados ao repositório
    - name: Adicionar arquivos ao repositório
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add --all  # Adiciona os arquivos gerados
        git commit -m "Atualização dos dados das contratações PNCP"
        git push https://github-actions:${{ secrets.GITHUB_TOKEN }}@github.com/eduardo130796/portal_licitacoes.git
