name: Atualizar Dados Contratações PNCP

on:
  schedule:
    - cron: "0 0 * * *"  # Isso fará o workflow rodar todos os dias à meia-noite
  workflow_dispatch:  # Isso permite rodar manualmente pela interface do GitHub
  push:
    branches:
      - main  # Ou a branch que você está utilizando

jobs:
  update_data:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do repositório
      uses: actions/checkout@v2

    - name: Configurar Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Defina a versão do Python que você usa

    - name: Instalar dependências
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Executar script Python
      run: |
        python scripts/atualizar_dados.py
